[project]
name = "acceleration-analysis"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pytz>=2024.2",
    "ubc-solar-data-tools>=1.9.1",
]
