[project]
name = "acceleration-analysis"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pytz>=2024.2",
    "ubc-solar-data-tools>=1.9.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
    "nbconvert>=7.16.6",
]
